"""update

Revision ID: 075852bbf3ef
Revises: d1194e00f082
Create Date: 2025-05-29 08:25:45.468832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075852bbf3ef'
down_revision: Union[str, None] = 'd1194e00f082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_submissions', sa.Column('creativity_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_submissions', 'creativity_score')
    # ### end Alembic commands ###
