"""add_extend_monitoring

Revision ID: 297cd56abc1d
Revises: 3cb66a71dade
Create Date: 2025-06-07 22:36:16.485353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297cd56abc1d'
down_revision: Union[str, None] = '3cb66a71dade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyactiveusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='_user_activity_date_uc')
    )
    op.create_index(op.f('ix_dailyactiveusers_activity_date'), 'dailyactiveusers', ['activity_date'], unique=False)
    op.create_index(op.f('ix_dailyactiveusers_id'), 'dailyactiveusers', ['id'], unique=False)
    op.add_column('game_players', sa.Column('player_order', sa.Integer(), nullable=True))
    op.add_column('game_players', sa.Column('emojis_sent', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('end_reason', sa.String(), nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('concurrent_websockets', sa.Integer(), nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('new_users_today', sa.Integer(), nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('dau', sa.Integer(), nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('mau', sa.Integer(), nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('p1_win_rate', sa.Float(), nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('api_error_rate_5xx_percent', sa.Float(), nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('gemini_avg_latency_ms', sa.Float(), nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('gemini_cache_hit_rate_percent', sa.Float(), nullable=True))
    op.drop_column('monitoringsnapshots', 'total_play_time_seconds')
    op.drop_column('monitoringsnapshots', 'avg_word_submission_time_ms')
    op.add_column('word_submissions', sa.Column('validation_latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_submissions', 'validation_latency_ms')
    op.add_column('monitoringsnapshots', sa.Column('avg_word_submission_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('monitoringsnapshots', sa.Column('total_play_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('monitoringsnapshots', 'gemini_cache_hit_rate_percent')
    op.drop_column('monitoringsnapshots', 'gemini_avg_latency_ms')
    op.drop_column('monitoringsnapshots', 'api_error_rate_5xx_percent')
    op.drop_column('monitoringsnapshots', 'p1_win_rate')
    op.drop_column('monitoringsnapshots', 'mau')
    op.drop_column('monitoringsnapshots', 'dau')
    op.drop_column('monitoringsnapshots', 'new_users_today')
    op.drop_column('monitoringsnapshots', 'concurrent_websockets')
    op.drop_column('games', 'end_reason')
    op.drop_column('game_players', 'emojis_sent')
    op.drop_column('game_players', 'player_order')
    op.drop_index(op.f('ix_dailyactiveusers_id'), table_name='dailyactiveusers')
    op.drop_index(op.f('ix_dailyactiveusers_activity_date'), table_name='dailyactiveusers')
    op.drop_table('dailyactiveusers')
    # ### end Alembic commands ###
