"""add_more_user_information

Revision ID: aae97b852a57
Revises: 297cd56abc1d
Create Date: 2025-06-08 22:32:31.447916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae97b852a57'
down_revision: Union[str, None] = '297cd56abc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('country', sa.String(length=2), nullable=True, comment='ISO 3166-1 alpha-2 country code'))
    op.add_column('users', sa.Column('mother_tongue', sa.String(length=10), nullable=True, comment="BCP-47 language code (e.g., 'en', 'es-MX')"))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=10), nullable=True, comment="BCP-47 language code (e.g., 'en', 'es-MX')"))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('language_level', sa.String(length=50), nullable=True, comment='e.g., A1, B2, native'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_level')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'mother_tongue')
    op.drop_column('users', 'country')
    op.drop_column('users', 'is_bot')
    # ### end Alembic commands ###
