"""add_language_to_game_model_and_sentence_prompt

Revision ID: d613a9d3f80b
Revises: 075852bbf3ef
Create Date: 2025-05-29 11:05:01.628740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd613a9d3f80b'
down_revision: Union[str, None] = '075852bbf3ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('language', sa.String(length=2), nullable=False, server_default='en'))
    op.create_index(op.f('ix_games_language'), 'games', ['language'], unique=False)
    op.add_column('sentenceprompts', sa.Column('language', sa.String(length=2), nullable=False, server_default='en'))
    op.create_index(op.f('ix_sentenceprompts_language'), 'sentenceprompts', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentenceprompts_language'), table_name='sentenceprompts')
    op.drop_column('sentenceprompts', 'language')
    op.drop_index(op.f('ix_games_language'), table_name='games')
    op.drop_column('games', 'language')
    # ### end Alembic commands ###
